services:

  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: database
    env_file:
      - .env.dev
    volumes:
      - database:/var/opt/mssql
    networks:
      - app-network
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P "$${SA_PASSWORD}" -Q "SELECT 1" -C || exit 1
      interval: 5s
      timeout: 2s
      retries: 3
      start_period: 10s
      
  migrator:
    image: datntdev/government-services/migrator:latest
    container_name: migrator
    depends_on:
      database:
        condition: service_healthy
    env_file:
      - .env.dev
    networks:
      - app-network
  
  backend:
    image: datntdev/government-services/backend:latest
    container_name: backend
    depends_on:
      migrator:
        condition: service_completed_successfully
    env_file:
      - .env.dev
    networks:
      - app-network
    ports:
      - 8080:8080

  frontend:
    image: datntdev/government-services/frontend:latest
    container_name: frontend
    ports:
      - 80:80

volumes:
  database:

networks:
  app-network:
    driver: bridge