name: Continuous Deployment 

on: 
  push:
    branches: [ "main" ]
    paths:
      - "angular/**"
      - "aspnet-core/**"
  workflow_dispatch:
    inputs:
      environment:
        description: Select environment to deploy docker images
        required: true
        default: 'stg'
        type: choice
        options:
        - prd
        - stg
      migrator: 
        description: Run the database migration
        required: true
        default: false
        type: boolean
      backend:
        description: Build and push the Backend docker image
        required: true
        default: true
        type: boolean
      frontend:
        description: Build and push the Frontend docker image
        required: true
        default: true
        type: boolean

env:
  ENVIRONMENT: >-
    ${{
      github.event_name == 'push' && github.ref == 'refs/heads/main' && 'prd'
      || github.event_name == 'workflow_dispatch' && inputs.environment
    }}

jobs:
  detect_changes:
    uses: ./.github/workflows/reuse-detect-changes.yml

  build_docker_images:
    needs: detect_changes
    uses: ./.github/workflows/reuse-build-images.yml
    if: ${{ false }}
    
    permissions:
      contents: read
      packages: write

    with:
      environment: ${{ inputs.environment }}
      migrator: false
      backend: ${{ inputs.backend || needs.detect_changes.outputs.backend == 'true' }}
      frontend: ${{ inputs.frontend || needs.detect_changes.outputs.frontend == 'true' }}

  database_migration:
    environment: ${{ inputs.environment }}
    needs: detect_changes
    if: false 
    # ${{ inputs.migrator || needs.detect_changes.outputs.migrator == 'true' }}

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x'
    - name: Build the Migrator project
      run: dotnet build
      working-directory: aspnet-core/src/Government.Services.Migrator
    - name: Running the migration from Migrator project
      run: dotnet run -q
      working-directory: aspnet-core/src/Government.Services.Migrator
      env:
        ConnectionStrings__Default: ${{ secrets.ASPNETCORE_ENVIRONMENT_CONNECTIONSTRINGS_DEFAULT }}
      
  deploy-docker-images:
    environment: ${{ inputs.environment }}
    # needs: [database_migration, build_docker_images]
    # if: |
    #   always() &&
    #   needs.build_docker_images.result == 'success' &&
    #   needs.database_migration.result != 'failure'

    runs-on: ubuntu-latest
    steps:
      - name: Deploy Portainer stack
        uses: datntdev0/actions-deploy-portainer@v0.1.0
        with:
          base-url: ${{ secrets.PORTAINER_BASE_URL }}
          access-token: ${{ secrets.PORTAINER_ACCESS_TOKEN }}
          endpoint-id: ${{ secrets.PORTAINER_ENDPOINT_ID }}
          stack-name: ${{ secrets.PORTAINER_STACK_NAME }}
          repository-url: https://github.com/${{ github.repository }}.git
          repository-ref: ${{ github.ref }}
          compose-file: .github/deploy/docker-compose.${{ inputs.environment }}.yml
          env-json: ${{ secrets.PORTAINER_ENV_JSON }}
  