name: Continuous Integration

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - "angular/**"
      - "aspnet-core/**"
  
jobs:
  detect_changes:
    uses: ./.github/workflows/reuse-detect-changes.yml
  
  build_docker_images:
    needs: detect_changes
    uses: ./.github/workflows/reuse-build-images.yml
    
    permissions:
      contents: read
      packages: write

    with:
      environment: dev
      migrator: ${{ needs.detect_changes.outputs.migrator == 'true' }}
      backend: ${{ needs.detect_changes.outputs.backend == 'true' }}
      frontend: ${{ needs.detect_changes.outputs.frontend == 'true' }}